services:
  server:
    container_name: shellshelf-server
    build: ./server
    ports:
      - "3001:3001"
    volumes:
      - shellshelf_data:/app/data
    restart: always

  client:
    container_name: shellshelf-client
    build: ./client
    ports:
      - "3000:80"
    restart: always

volumes:
  shellshelf_data:
